version: "3.8"

services:
  frontend:
    image: setu3011/smart-reminder-frontend
    ports:
      - "3000:80"

  backend:
    image: setu3011/smart-reminder-backend
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  mongo:
    image: mongo:6.0.13
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
